# NumPy Basics

In [1]:
## Importing the library
import numpy as np

### Terminologies

- <b>Axis:</b> An integer value representing each dimension of the array. <b>Ex:</b> For a 2D array, rows are axis 0 whereas columns are axis 1.
- <b>Shape:</b> Tuple representing the dimension values of an array along every axis. <b>Ex:</b> A 2D array with M rows and N columns has shape (M,N).
- <b>Vector:</b> An array with a single dimension.

### Creating a NumPy array

In [2]:
## You create a numpy array by passing a list to the function np.array
array = np.array([1,2,3])
print(array)

[1 2 3]


In [4]:
## Creating a 2D array and printing its shape.
## You can create a 2D array by passing a "list of lists" to np.array

row1 = [1,2,3]
row2 = [4,5,6]
matrix = [row1, row2] ##This is a list of lists.

array2D = np.array(matrix)
print(array2D)
print('\nShape of the array:', array2D.shape)

[[1 2 3]
 [4 5 6]]

Shape of the array: (2, 3)


In [3]:
## Alternatively, you can create the array as shown below:

array2D = np.array([[1,2,3],[4,5,6]])
print(array2D)
print('\nShape of the array:', array2D.shape)

[[1 2 3]
 [4 5 6]]

Shape of the array: (2, 3)


In [6]:
## Let's create some 3D arrays filled with ones and zeros
## We need to pass the shape of the array to the functions np.ones and np.zeros

array3D_ones = np.ones(shape = (2, 2, 2))
array3D_zeros = np.zeros(shape = (2, 2, 2))

print(array3D_zeros)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


### NumPy arrays vs Lists

In [7]:
## Let us recreate the above 2D array

row1 = [1,2,3]
row2 = [4,5,6]
matrix = [row1, row2]
array2D = np.array(matrix)

In [8]:
## Let us print some elements of both "matrix" and "array2D"
## Look how the notation is different (Clearly, NumPy arrays are easy to access):

print('First Element of List:', matrix[0][0])
print('First Element of Numpy Array:', array2D[0,0])

print('Last Element of List:', matrix[-1][-1])
print('Last Element of Numpy Array:', array2D[-1,-1])

First Element of List: 1
First Element of Numpy Array: 1
Last Element of List: 6
Last Element of Numpy Array: 6


## Loading images

### Single image loading

In [9]:
## Importing OpenCV
import cv2
import os

In [10]:
## Loading the image and printing its shape

img = cv2.imread('images/Image_1.jpg', 1) # 0 -> B/W image, 1 -> Colour image
print(img.shape)

(128, 128, 3)


In [11]:
### Multiple image loading

file_list = [os.path.join('images', filename) for filename in os.listdir('images')]
list_of_imgs = []

for file in file_list:
    list_of_imgs.append(cv2.imread(file, 1))

list_of_imgs = np.array(list_of_imgs)
print(list_of_imgs.shape)

(5, 128, 128, 3)


## Basic arithmetic operations:

### Basic Broadcasting
 

In [12]:
## Adding a constant to all elements of an array

array1 = np.ones((2,2))
array2 = array1 + 6
print(array2)

[[7. 7.]
 [7. 7.]]


In [13]:
## Multiplying a constance to all elements of an array

array1 = np.ones((2,2))
array2 = array1 * 3
print(array2)

[[3. 3.]
 [3. 3.]]


### Simple Arithmetic

In [14]:
## Adding two arrays. You can subtract them in a similar fashion.

array1 = np.ones((2,2)) * 3
array2 = np.ones((2,2)) * 2
array3 = array1 + array2
print(array3)

[[5. 5.]
 [5. 5.]]


In [15]:
## Element-wise multiplication of two arrays. You can divide them in a similar fashion.

array1 = np.ones((2,2)) * 3
array2 = np.ones((2,2)) * 2
array3 = array1 * array2
print(array3)

[[6. 6.]
 [6. 6.]]


In [16]:
## Matrix multiplication

array1 = np.ones((2,2)) * 3
array2 = np.ones((2,2)) * 2
array3 = array1 @ array2
print(array3)

[[12. 12.]
 [12. 12.]]


## Other operations:

### Concatenation

In [ ]:
## Code to concatenate two arrays along an axis.
## Two arrays can only be concatenated if all axes other than the target axis are the same in both arrays

array1 = np.ones((1,2,4))
array2 = np.ones((1,2,7))

print('Shape of array1:', array1.shape)
print('Shape of array2:', array2.shape)

concatenated_result = np.concatenate((array1, array2), axis=2)
print('Shape of result:', concatenated_result.shape)

### Transpose

In [17]:
## Transposing refers to reordering the axes.
## For 2D arrays, it's as simple as below:

array = np.array([[1,2,3], [4,5,6]])
print('Shape of the original array:', array.shape)
print('Shape of the transposed array', array.T.shape)

print('Original array:')
print(array)

print('Transposed array:')
print(array.T)

Shape of the original array: (2, 3)
Shape of the transposed array (3, 2)
Original array:
[[1 2 3]
 [4 5 6]]
Transposed array:
[[1 4]
 [2 5]
 [3 6]]


In [19]:
## The object ".T" reverses the axes. For 3D arrays and larger, there are many more ways to transpose.

array3D = np.ones((6,4,9))
array3D_transpose = np.transpose(array3D, (1,2,0))

print('Shape of the original array:', array3D.shape)
print('Shape of the transposed array:', array3D_transpose.shape)

Shape of the original array: (6, 4, 9)
Shape of the transposed array: (4, 9, 6)


### Ravel

In [20]:
## Converts array of any dimension into a vector

array = np.ones((4,5,6))
array_ravelled = array.ravel()
print('Shape of the ravelled array:', array_ravelled.shape)

Shape of the ravelled array: (120,)


### Reshape

In [21]:
## Reshapes the array. The condition is that, the product of the axis values in the new array
## must be equal to the product of the axis values in the old array.

array = np.ones((4,5,6))
array_reshaped = array.reshape(60, 2)

print('Shape of the new array:', array_reshaped.shape)

Shape of the new array: (60, 2)


In [22]:
## If you don't know the value of "only one axis", you can specify '-1' to the reshape function.

array = np.ones((4,5,6))
array_reshaped = array.reshape((3, 4, -1))

print('Shape of the new array:', array_reshaped.shape)

Shape of the new array: (3, 4, 10)


### Slicing

In [23]:
## Slicing is simply removing a part of an array.
## Here's a 1D example.

array = np.array([11,32,53,42,95])

first_two = array[:2]
second_and_third = array[2:4]
last_two = array[-2:]
all_elements = array[:]

print('First two elements:', first_two)
print('Second and third elements:', second_and_third)
print('Last two elements:', last_two)
print('All elements:', all_elements)

First two elements: [11 32]
Second and third elements: [53 42]
Last two elements: [42 95]
All elements: [11 32 53 42 95]


In [24]:
## Slicing multidimensional arrays.

array = np.ones((5,6,7))
sliced = array[:2,:2,:]

print('Shape of original array:', array.shape)
print('Shape of sliced array:', sliced.shape)

Shape of original array: (5, 6, 7)
Shape of sliced array: (2, 2, 7)


### Saving and loading arrays

In [25]:
## Saving an array

array = np.ones((3,3,3))
np.save('trial.npy', array)

In [26]:
## Loading an array (Run the above cell first)

array = np.load('trial.npy')
print('Shape of loaded array:', array.shape)

Shape of loaded array: (3, 3, 3)


### Further material 

- Checkout the official NumPy documentation for more powerful functions, such as np.where
- Helpful resource material: http://cs231n.github.io/python-numpy-tutorial/